"""add photo-user relationship

Revision ID: 6f1736796821
Revises: 1f5dc3bd3684
Create Date: 2025-10-27 23:48:25.104611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1736796821'
down_revision: Union[str, Sequence[str], None] = '1f5dc3bd3684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(op.f('photo_tags_photo_id_fkey'), 'photo_tags', type_='foreignkey')
    op.drop_constraint(op.f('photo_tags_tag_id_fkey'), 'photo_tags', type_='foreignkey')
    op.create_foreign_key(None, 'photo_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'photo_tags', 'photos', ['photo_id'], ['id'])
    op.add_column('tags', sa.Column('slug', sa.String(length=120), nullable=True))
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tags', 'slug')
    op.drop_constraint(None, 'photo_tags', type_='foreignkey')
    op.drop_constraint(None, 'photo_tags', type_='foreignkey')
    op.create_foreign_key(op.f('photo_tags_tag_id_fkey'), 'photo_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('photo_tags_photo_id_fkey'), 'photo_tags', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###
