"""Fix photo_tags PK and add slug to photos

Revision ID: 7764f2863914
Revises: b9ca1c9a071e
Create Date: 2025-11-02 17:30:49.021913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7764f2863914'
down_revision: Union[str, Sequence[str], None] = 'b9ca1c9a071e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('slug', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'photos', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_slug_key', 'photos', type_='unique')
    op.drop_column('photos', 'slug')
    # ### end Alembic commands ###
