"""rafactor album table

Revision ID: b9ca1c9a071e
Revises: 6f1736796821
Create Date: 2025-10-28 10:36:34.746239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ca1c9a071e'
down_revision: Union[str, Sequence[str], None] = '6f1736796821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('albums', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_albums_slug'), 'albums', ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_index(op.f('ix_albums_slug'), table_name='albums')
    op.drop_column('albums', 'status')
    op.drop_column('albums', 'slug')
    # ### end Alembic commands ###
