"""fix relationships

Revision ID: f26b8617eddc
Revises: 90d577bd88dc
Create Date: 2025-10-27 23:34:20.710607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26b8617eddc'
down_revision: Union[str, Sequence[str], None] = '90d577bd88dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('albums_user_id_fkey'), 'albums', type_='foreignkey')
    op.create_foreign_key(None, 'albums', 'categories', ['category_id'], ['id'])
    op.drop_column('albums', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_foreign_key(op.f('albums_user_id_fkey'), 'albums', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('albums', 'category_id')
    # ### end Alembic commands ###
